use_frameworks!

platform :ios, '10.0'

target 'DeepmediKit_Example' do
  pod 'DeepmediKit', :path => '../'

  target 'DeepmediKit_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end