//
//  TFLiteModelRunner.swift
//  DeepmediKit
//
//  Created by 딥메디 on 5/26/26.
//

import Foundation
import TensorFlowLite

public final class TFLiteModelRunner {
    public struct CoreOutput {
        public let ppg100: [Float]
        public let peakLogits: [Float]
        public let ppg30: [Float]
    }

    private let interpreter: Interpreter

    public init(
        modelName: String = "model_core",
        threadCount: Int = 2
    ) throws {
        guard let modelPath = Self.resolveModelPath(modelName: modelName) else {
            throw NSError(
                domain: "TFLiteModelRunner",
                code: -1,
                userInfo: [NSLocalizedDescriptionKey: "Could not find model: \(modelName).tflite"]
            )
        }

        var options = Interpreter.Options()
        options.threadCount = threadCount

        let interpreter = try Interpreter(modelPath: modelPath, options: options)
        try interpreter.allocateTensors()
        self.interpreter = interpreter
    }

    public func inputTensorByteCount(at index: Int = 0) throws -> Int {
        try interpreter.input(at: index).data.count
    }

    public func run(inputData: Data, inputIndex: Int = 0, outputIndex: Int = 0) throws -> Data {
        let expectedBytes = try inputTensorByteCount(at: inputIndex)
        guard inputData.count == expectedBytes else {
            throw NSError(
                domain: "TFLiteModelRunner",
                code: -2,
                userInfo: [NSLocalizedDescriptionKey: "Input byte count mismatch. expected=\(expectedBytes), got=\(inputData.count)"]
            )
        }

        try interpreter.copy(inputData, toInputAt: inputIndex)
        try interpreter.invoke()
        return try interpreter.output(at: outputIndex).data
    }

    public func runCore(frames: Data, timestamps: Data) throws -> CoreOutput {
        let runner = try interpreter.signatureRunner(with: "serving_default")
        try runner.resizeInput(named: "frames", toShape: [1, 451, 36, 36, 3])
        try runner.resizeInput(named: "timestamps", toShape: [1, 451])
        try runner.invoke(with: [
            "frames": frames,
            "timestamps": timestamps
        ])

        let ppg100Data = try runner.output(named: "ppg_100").data
        let peakLogitsData = try runner.output(named: "peak_logits").data
        let ppg30Data = try runner.output(named: "ppg_30").data

        return .init(
            ppg100: Self.floatArray(from: ppg100Data),
            peakLogits: Self.floatArray(from: peakLogitsData),
            ppg30: Self.floatArray(from: ppg30Data)
        )
    }

    private static func floatArray(from data: Data) -> [Float] {
        let count = data.count / MemoryLayout<Float>.stride
        return data.withUnsafeBytes { raw in
            guard let base = raw.baseAddress else { return [] }
            let ptr = base.assumingMemoryBound(to: Float.self)
            return Array(UnsafeBufferPointer(start: ptr, count: count))
        }
    }

    private static func resolveModelPath(modelName: String) -> String? {
        // 1) Resource bundle generated by CocoaPods: DeepmediKit.bundle
        if let bundleURL = Bundle.main.url(forResource: "DeepmediKit", withExtension: "bundle"),
           let bundle = Bundle(url: bundleURL),
           let path = bundle.path(forResource: modelName, ofType: "tflite") {
            return path
        }

        // 2) Framework bundle (works when used as framework target)
        let frameworkBundle = Bundle(for: TFLiteModelRunner.self)
        if let path = frameworkBundle.path(forResource: modelName, ofType: "tflite") {
            return path
        }

        // 3) App main bundle fallback
        return Bundle.main.path(forResource: modelName, ofType: "tflite")
    }
}

public struct PhysMorphNetResult: Equatable {
    public let sdnn: Double
    public let rmssd: Double
    public let hr: Double
    public let rrList: [Double]
    public let ppg: [Double]
    public let quality: Double
    
    public init(
        sdnn: Double,
        rmssd: Double,
        hr: Double,
        quality: Double,
        rrList: [Double],
        ppg: [Double]
    ) {
        self.sdnn = sdnn
        self.rmssd = rmssd
        self.hr = hr
        self.quality = quality
        self.rrList = rrList
        self.ppg = ppg
    }
}

internal struct FaceCoreMetrics: Equatable {
    public let inputFrameCount: Int
    public let usedFrameCount: Int
    public let clipSpanS: Float
    public let durationS: Double
    public let measuredFPS: Double
    
    public let ppgHat: [Double]

    public let sdnnMS: Double?
    public let rmssdMS: Double?
    public let meanHRBPM: Double?
    public let qualityConf: Double
    public let keepRate: Double
    public let rrCV: Double?
    public let ok: Bool
    public let nPeaks: Int
    public let nRRSmooth: Int
    public let peakTimesS: [Double]
    public let rrSmoothMS: [Double]

    public init(
        inputFrameCount: Int,
        usedFrameCount: Int,
        clipSpanS: Float,
        durationS: Double,
        measuredFPS: Double,
        sdnnMS: Double?,
        rmssdMS: Double?,
        meanHRBPM: Double?,
        qualityConf: Double,
        keepRate: Double,
        rrCV: Double?,
        ok: Bool,
        nPeaks: Int,
        nRRSmooth: Int,
        peakTimesS: [Double],
        rrSmoothMS: [Double],
        ppgHat: [Double]
    ) {
        self.inputFrameCount = inputFrameCount
        self.usedFrameCount = usedFrameCount
        self.clipSpanS = clipSpanS
        self.durationS = durationS
        self.measuredFPS = measuredFPS
        self.sdnnMS = sdnnMS
        self.rmssdMS = rmssdMS
        self.meanHRBPM = meanHRBPM
        self.qualityConf = qualityConf
        self.keepRate = keepRate
        self.rrCV = rrCV
        self.ok = ok
        self.nPeaks = nPeaks
        self.nRRSmooth = nRRSmooth
        self.peakTimesS = peakTimesS
        self.rrSmoothMS = rrSmoothMS
        self.ppgHat = ppgHat
    }
}

internal enum FaceCoreMetricsError: Error {
    case noFrame
    case invalidFrameSize(expected: Int, actual: Int)
}

internal final class FaceCoreMetricsCalculator {
    private static let targetCount = 451
    private static let frameByteLength = 36 * 36 * 3
    private static let nominalStepUS: UInt64 = 33_333
    private static let targetFS = 100.0

    private struct PreparedCoreInput {
        let framesData: Data
        let timestampsData: Data
        let clipSpanS: Float
        let durationS: Double
        let measuredFPS: Double
        let inputFrameCount: Int
        let usedFrameCount: Int
    }

    private struct HRVSummary {
        let sdnnMS: Double?
        let rmssdMS: Double?
        let meanHRBPM: Double?
        let qualityConf: Double
        let keepRate: Double
        let rrCV: Double?
        let ok: Bool
        let nPeaks: Int
        let nRRSmooth: Int
        let peakTimesS: [Double]
        let rrSmoothMS: [Double]
    }

    static func analyze(
        frames: [SampleBufferConverter.FaceBinFrame],
        runner: TFLiteModelRunner
    ) throws -> PhysMorphNetResult {
        let prepared = try prepareCoreInputs(frames: frames)

        let core = try runner.runCore(
            frames: prepared.framesData,
            timestamps: prepared.timestampsData
        )
        let normalized = normalizeCoreOutputs(
            ppg100: core.ppg100,
            peakLogits: core.peakLogits
        )
        let peakIndices = detectPeaks(
            peakProb: normalized.peakProb,
            ppgHat: normalized.ppgHat
        )
        let hrv = computeHRV(
            peakIndices: peakIndices,
            peakProb: normalized.peakProb
        )
        
        return .init(
            sdnn: hrv.sdnnMS ?? 0.0,
            rmssd: hrv.rmssdMS ?? 0.0,
            hr: hrv.meanHRBPM ?? 0.0,
            quality: hrv.qualityConf,
            rrList: hrv.rrSmoothMS,
            ppg: normalized.ppgHat
        )
    }

    private static func prepareCoreInputs(
        frames: [SampleBufferConverter.FaceBinFrame]
    ) throws -> PreparedCoreInput {
        guard !frames.isEmpty else { throw FaceCoreMetricsError.noFrame }
        for frame in frames where frame.rgb36x36.count != frameByteLength {
            throw FaceCoreMetricsError.invalidFrameSize(
                expected: frameByteLength,
                actual: frame.rgb36x36.count
            )
        }

        let n = frames.count
        let durationS: Double
        let measuredFPS: Double
        if n >= 2 {
            let firstTS = frames.first?.timestampUS ?? 0
            let lastTS = frames.last?.timestampUS ?? firstTS
            let diff = Double(lastTS - firstTS) / 1_000_000.0
            durationS = diff
            measuredFPS = diff > 0 ? Double(n - 1) / diff : 0
        } else {
            durationS = 0
            measuredFPS = 0
        }

        let used = min(n, targetCount)
        var clipFrames = [SampleBufferConverter.FaceBinFrame]()
        clipFrames.reserveCapacity(targetCount)
        clipFrames.append(contentsOf: frames.prefix(used))

        if n < targetCount, let last = frames.last {
            let missing = targetCount - n
            for i in 1...missing {
                clipFrames.append(
                    .init(
                        rgb36x36: last.rgb36x36,
                        timestampUS: last.timestampUS + (UInt64(i) * nominalStepUS)
                    )
                )
            }
        }

        var framesData = Data(capacity: targetCount * frameByteLength)
        for frame in clipFrames {
            framesData.append(contentsOf: frame.rgb36x36)
        }

        let ts0 = clipFrames.first?.timestampUS ?? 0
        let relativeS = clipFrames.map { Float(Double($0.timestampUS - ts0) / 1_000_000.0) }
        let clipSpanS = relativeS.last ?? 0
        let timestampsData = relativeS.withUnsafeBufferPointer { Data(buffer: $0) }

        return .init(
            framesData: framesData,
            timestampsData: timestampsData,
            clipSpanS: clipSpanS,
            durationS: durationS,
            measuredFPS: measuredFPS,
            inputFrameCount: n,
            usedFrameCount: used
        )
    }

    private static func normalizeCoreOutputs(
        ppg100: [Float],
        peakLogits: [Float]
    ) -> (ppgHat: [Double], peakProb: [Double]) {
        guard !ppg100.isEmpty else { return ([], []) }

        let ppg = ppg100.map(Double.init)
        let mean = ppg.reduce(0, +) / Double(ppg.count)
        let variance = ppg.map { ($0 - mean) * ($0 - mean) }.reduce(0, +) / Double(ppg.count)
        let std = sqrt(variance) + 1e-8
        let ppgHat = ppg.map { ($0 - mean) / std }
        let peakProb = peakLogits.map { 1.0 / (1.0 + exp(-Double($0))) }
        return (ppgHat, peakProb)
    }

    private static func detectPeaks(
        peakProb: [Double],
        ppgHat: [Double],
        threshold: Double = 0.3,
        minDistS: Double = 0.3,
        snapHalfWindowS: Double = 0.05
    ) -> [Int] {
        guard peakProb.count >= 3, peakProb.count == ppgHat.count else { return [] }
        let minDist = max(1, Int(minDistS * targetFS))
        var candidates: [Int] = []

        for i in 1..<(peakProb.count - 1) {
            let isPeak = peakProb[i] >= threshold &&
                peakProb[i] > peakProb[i - 1] &&
                peakProb[i] > peakProb[i + 1]
            guard isPeak else { continue }

            if let last = candidates.last {
                if i - last >= minDist {
                    candidates.append(i)
                } else if peakProb[i] > peakProb[last] {
                    candidates[candidates.count - 1] = i
                }
            } else {
                candidates.append(i)
            }
        }

        let halfWindow = max(1, Int(snapHalfWindowS * targetFS))
        var snapped: [Int] = []
        snapped.reserveCapacity(candidates.count)
        for p in candidates {
            let lo = max(0, p - halfWindow)
            let hi = min(ppgHat.count - 1, p + halfWindow)
            var bestIndex = p
            var bestValue = ppgHat[p]
            if lo <= hi {
                for idx in lo...hi where ppgHat[idx] < bestValue {
                    bestValue = ppgHat[idx]
                    bestIndex = idx
                }
            }
            snapped.append(bestIndex)
        }
        return snapped
    }

    private static func filterRR(
        rrMS: [Double],
        rrTimesS: [Double]?
    ) -> [Double] {
        let minMS = 300.0
        let maxMS = 1500.0
        let gateFactor = 0.2
        let malikTH = 0.2
        let clipWindowS = 15.0

        var rr = rrMS.enumerated()
            .filter { $0.element > minMS && $0.element < maxMS }
            .map(\.element)
        var times = rrTimesS
        if let rrTimesS {
            times = rrMS.enumerated()
                .filter { $0.element > minMS && $0.element < maxMS }
                .map { rrTimesS[$0.offset] }
        }
        guard rr.count >= 3 else { return rr }

        if let times, times.count == rr.count {
            let t0 = times[0]
            var keep = Array(repeating: true, count: rr.count)
            let clipIndex = times.map { Int(floor(($0 - t0) / clipWindowS)) }
            let uniqueClips = Array(Set(clipIndex))
            for clip in uniqueClips {
                let indices = clipIndex.enumerated().compactMap { $0.element == clip ? $0.offset : nil }
                guard indices.count >= 3 else { continue }
                let localRR = indices.map { rr[$0] }.sorted()
                let median = localRR[localRR.count / 2]
                let lo = median * (1.0 - gateFactor)
                let hi = median * (1.0 + gateFactor)
                for idx in indices where rr[idx] < lo || rr[idx] > hi {
                    keep[idx] = false
                }
            }
            rr = rr.enumerated().filter { keep[$0.offset] }.map(\.element)
        } else {
            let sorted = rr.sorted()
            let median = sorted[sorted.count / 2]
            let lo = median * (1.0 - gateFactor)
            let hi = median * (1.0 + gateFactor)
            rr = rr.filter { $0 >= lo && $0 <= hi }
        }
        guard rr.count >= 2 else { return rr }

        var filtered: [Double] = []
        filtered.reserveCapacity(rr.count)
        for i in rr.indices {
            if i == 0 {
                filtered.append(rr[i])
                continue
            }
            let prev = rr[i - 1]
            let ratio = abs(rr[i] - prev) / (prev + 1e-6)
            if ratio <= malikTH {
                filtered.append(rr[i])
            }
        }
        return filtered
    }

    private static func smoothRR(_ rrMS: [Double]) -> [Double] {
        guard rrMS.count >= 3 else { return rrMS }
        var smoothed: [Double] = []
        smoothed.reserveCapacity(rrMS.count)
        for i in rrMS.indices {
            let left = i == 0 ? rrMS[i] : rrMS[i - 1]
            let center = rrMS[i]
            let right = i == (rrMS.count - 1) ? rrMS[i] : rrMS[i + 1]
            smoothed.append((0.25 * left) + (0.5 * center) + (0.25 * right))
        }
        return smoothed
    }

    private static func computeHRV(
        peakIndices: [Int],
        peakProb: [Double]
    ) -> HRVSummary {
        let peakTimesS = peakIndices.map { Double($0) / targetFS }
        let qualityConf: Double
        if peakIndices.isEmpty {
            qualityConf = 0.0
        } else {
            qualityConf = peakIndices.map { peakProb[$0] }.reduce(0, +) / Double(peakIndices.count)
        }

        guard peakIndices.count >= 2 else {
            return .init(
                sdnnMS: nil, rmssdMS: nil, meanHRBPM: nil,
                qualityConf: qualityConf, keepRate: 0, rrCV: nil, ok: false,
                nPeaks: peakIndices.count, nRRSmooth: 0, peakTimesS: peakTimesS, rrSmoothMS: []
            )
        }

        var rrRawMS: [Double] = []
        rrRawMS.reserveCapacity(peakTimesS.count - 1)
        for i in 1..<peakTimesS.count {
            rrRawMS.append((peakTimesS[i] - peakTimesS[i - 1]) * 1000.0)
        }
        let rrFiltered = filterRR(rrMS: rrRawMS, rrTimesS: Array(peakTimesS.dropLast()))
        let keepRate = rrRawMS.isEmpty ? 0.0 : Double(rrFiltered.count) / Double(rrRawMS.count)
        guard rrFiltered.count >= 3 else {
            return .init(
                sdnnMS: nil, rmssdMS: nil, meanHRBPM: nil,
                qualityConf: qualityConf, keepRate: keepRate, rrCV: nil, ok: false,
                nPeaks: peakIndices.count, nRRSmooth: 0, peakTimesS: peakTimesS, rrSmoothMS: []
            )
        }

        let rrSmoothed = smoothRR(rrFiltered)
        let rrDiff = zip(rrSmoothed.dropFirst(), rrSmoothed).map { $0 - $1 }
        let rmssd = sqrt(rrDiff.map { $0 * $0 }.reduce(0, +) / Double(rrDiff.count))
        let meanRR = rrSmoothed.reduce(0, +) / Double(rrSmoothed.count)
        let variance = rrSmoothed.map { ($0 - meanRR) * ($0 - meanRR) }.reduce(0, +) / Double(rrSmoothed.count - 1)
        let sdnn = sqrt(max(variance, 0))
        let meanHR = 60000.0 / (meanRR + 1e-8)
        let popStd = sqrt(rrSmoothed.map { ($0 - meanRR) * ($0 - meanRR) }.reduce(0, +) / Double(rrSmoothed.count))
        let rrCV = popStd / (meanRR + 1e-6)

        let ok = qualityConf >= 0.40 &&
            keepRate >= 0.70 &&
            rrCV.isFinite &&
            rrCV <= 0.25

        return .init(
            sdnnMS: sdnn,
            rmssdMS: rmssd,
            meanHRBPM: meanHR,
            qualityConf: qualityConf,
            keepRate: keepRate,
            rrCV: rrCV,
            ok: ok,
            nPeaks: peakIndices.count,
            nRRSmooth: rrSmoothed.count,
            peakTimesS: peakTimesS,
            rrSmoothMS: rrSmoothed
        )
    }
}
